apiVersion: cdap.cdap.io/v1alpha1
kind: CDAPMaster
metadata:
  labels:
    cdap.version: "6.0.0"
  name: master-1
spec:
  image: gcr.io/cloud-data-fusion-images/cloud-data-fusion:latest
  userInterfaceImage: gcr.io/cloud-data-fusion-images/cloud-data-fusion-ui:latest
  appFabric:
    resources:
      requests:
        memory: "3Gi"
        cpu: "1000m"
  logs:
    resources:
      requests:
        memory: "2Gi"
        cpu: "500m"
    storageSize: "100Gi"
  messaging:
    resources:
      requests:
        memory: "1500Mi"
        cpu: "500m"
    storageSize: "60Gi"
  metadata:
    resources:
      requests:
        memory: "1500Mi"
        cpu: "500m"
  metrics:
    resources:
      requests:
        memory: "2Gi"
        cpu: "500m"
    storageSize: "100Gi"
  preview:
    resources:
      requests:
        memory: "2Gi"
        cpu: "500m"
    storageSize: "10Gi"
  userInterface:
    replicas: 2
  router:
    replicas: 2
  serviceAccountName: cdap
  securitySecret: cdap-secret
  locationURI: hdfs://hadoop:9000
  config:
    enable.preview: "true"
    data.storage.implementation: postgresql
    data.storage.sql.jdbc.connection.url: jdbc:postgresql://postgres-postgresql:5432/cdap
    data.storage.sql.jdbc.driver.name: org.postgresql.Driver
    metadata.storage.implementation: elastic
    metadata.elasticsearch.cluster.hosts: escluster-master:9200
