apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cdap-controller
  namespace: cdap-test
spec:
  template:
    spec:
      containers:
      # Change the value of image field below to your controller image URL
      - image: gcr.io/cdapio/cdap-controller:latest
        name: manager
