apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: cdap-controller
    controller-tools.k8s.io: "1.0"
  name: cdap-test
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cdap-controller
  namespace: cdap-test
  labels:
    control-plane: cdap-controller
    controller-tools.k8s.io: "1.0"
spec:
  selector:
    matchLabels:
      control-plane: cdap-controller
      controller-tools.k8s.io: "1.0"
  serviceName: cdap-controller-service
  template:
    metadata:
      labels:
        control-plane: cdap-controller
        controller-tools.k8s.io: "1.0"
    spec:
      containers:
      - command:
        - /manager
        image: gcr.io/cdapio/cdap-controller:latest
        name: manager
        env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
      terminationGracePeriodSeconds: 10
